stages:
  - build
  - test

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"
  NODE_ENV: "test"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules
    - cache/Cypress
    - build

install:
  image: cypress/browsers:node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge-130.0.2849.56-1
  stage: build
  script:
    - npm ci
    - npm install mochawesome --save-dev

test:
  image: cypress/browsers:node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge-130.0.2849.56-1
  stage: test
  script:
    - npx cypress run --browser chrome --reporter mochawesome --reporter-options reportDir=cypress/results,overwrite=false,html=true,json=true
  artifacts:
    when: always
    paths:
      - mochawesome-report/
      - cypress/results/
      - cypress/screenshots/
      - cypress/videos/
    expire_in: 30 days
